package id.ac.ui.cs.prices.winvmj.composer.monitoring.injector;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.stmt.CatchClause;
import com.github.javaparser.ast.stmt.Statement;
import com.github.javaparser.ast.stmt.TryStmt;

import id.ac.ui.cs.prices.winvmj.composer.microservicepreprocessor.JavaParserUtil;
import id.ac.ui.cs.prices.winvmj.composer.runtime.WinVMJConsole;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.runtime.CoreException;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Injects DB metrics into existing {Entity}RepositoryImpl files (generated by RepositoryInjector).
 * Wraps each override method body with timing + OTel counter/histogram recording.
 * Also injects into ServiceImpl/ResourceImpl for method-level DB awareness.
 */
public class DbMetricsInjector {

    private static final List<String> IMPORTS = List.of(
        "io.opentelemetry.api.GlobalOpenTelemetry",
        "io.opentelemetry.api.metrics.Meter",
        "io.opentelemetry.api.metrics.LongCounter",
        "io.opentelemetry.api.metrics.LongHistogram",
        "io.opentelemetry.api.common.Attributes",
        "io.opentelemetry.api.common.AttributeKey"
    );

    private static final String[] FIELD_DECLARATIONS = {
        "private LongCounter _dbQueryCounter;",
        "private LongCounter _dbQueryErrorCounter;",
        "private LongHistogram _dbQueryDurationHistogram;"
    };

    private static final String[] CONSTRUCTOR_INIT = {
        "Meter _dbMeter = GlobalOpenTelemetry.get().getMeter(\"monitoring\");",
        "_dbQueryCounter = _dbMeter.counterBuilder(\"db_queries_total\").setDescription(\"Total number of database queries\").build();",
        "_dbQueryErrorCounter = _dbMeter.counterBuilder(\"db_query_errors_total\").setDescription(\"Total number of failed database queries\").build();",
        "_dbQueryDurationHistogram = _dbMeter.histogramBuilder(\"db_query_duration_ms\").setDescription(\"Database query duration in milliseconds\").ofLongs().build();"
    };

    /**
     * Map method name → DB operation for RepositoryImpl overrides.
     */
    private static final Map<String, String> METHOD_TO_OPERATION = Map.of(
        "saveObject", "INSERT",
        "updateObject", "UPDATE",
        "getObject", "SELECT",
        "getAllObject", "SELECT",
        "deleteObject", "DELETE",
        "executeQuery", "EXECUTE"
    );

    public static void inject(IFolder moduleDir, String featureName) {
        try {
            IFile moduleInfo = moduleDir.getFile("module-info.java");
            if (moduleInfo.exists()) {
                AstUtils.addModuleRequires(moduleInfo, List.of("io.opentelemetry.api"));
            }

            for (IFile file : AstUtils.findRepositoryImplFiles(moduleDir)) {
                processFile(file, featureName);
            }
        } catch (CoreException e) {
            WinVMJConsole.println("[DbMetricsInjector] Error scanning " + moduleDir.getName() + ": " + e.getMessage());
        }
    }

    private static void processFile(IFile file, String featureName) {
        WinVMJConsole.println("[DbMetricsInjector] Processing " + file.getFullPath());

        CompilationUnit cu = JavaParserUtil.parse(file);

        AstUtils.addImports(cu, IMPORTS);
        AstUtils.addInstanceFields(cu, FIELD_DECLARATIONS, "_dbQueryCounter");
        AstUtils.addConstructorInit(cu, CONSTRUCTOR_INIT, "_dbQueryCounter = _dbMeter");

        int count = 0;
        for (MethodDeclaration method : cu.findAll(MethodDeclaration.class)) {
            Optional<BlockStmt> bodyOpt = method.getBody();
            if (bodyOpt.isEmpty()) continue;

            String operation = METHOD_TO_OPERATION.get(method.getNameAsString());
            if (operation == null) continue; // skip constructor or unknown methods

            wrapMethod(method, featureName, operation);
            count++;
        }

        if (count > 0) {
            AstUtils.overwriteFile(file, cu);
            WinVMJConsole.println("[DbMetricsInjector] Wrapped " + count + " methods in " + file.getName());
        }
    }

    private static void wrapMethod(MethodDeclaration method, String featureName, String operation) {
        Optional<BlockStmt> bodyOpt = method.getBody();
        if (bodyOpt.isEmpty()) return;

        NodeList<Statement> originalStmts = new NodeList<>(bodyOpt.get().getStatements());

        String attrsExpr = "Attributes.of("
            + "AttributeKey.stringKey(\"feature\"), FEATURE_NAME, "
            + "AttributeKey.stringKey(\"db.operation\"), \"" + operation + "\", "
            + "AttributeKey.stringKey(\"db.table\"), TABLE_NAME)";

        BlockStmt newBody = new BlockStmt();
        newBody.addStatement(StaticJavaParser.parseStatement(
            "long _dbStart = System.currentTimeMillis();"));

        // try { originalBody }
        BlockStmt tryBlock = new BlockStmt();
        originalStmts.forEach(tryBlock::addStatement);

        // catch (Throwable _dbT) { errorCounter++; rethrow }
        BlockStmt catchBlock = new BlockStmt();
        catchBlock.addStatement(StaticJavaParser.parseStatement(
            "_dbQueryErrorCounter.add(1, " + attrsExpr + ");"));
        catchBlock.addStatement(StaticJavaParser.parseStatement("throw _dbT;"));

        CatchClause catchClause = new CatchClause(
            new Parameter(StaticJavaParser.parseType("Throwable"), "_dbT"), catchBlock);

        // finally { always count + duration }
        BlockStmt finallyBlock = new BlockStmt();
        finallyBlock.addStatement(StaticJavaParser.parseStatement(
            "_dbQueryCounter.add(1, " + attrsExpr + ");"));
        finallyBlock.addStatement(StaticJavaParser.parseStatement(
            "_dbQueryDurationHistogram.record(System.currentTimeMillis() - _dbStart, " + attrsExpr + ");"));

        newBody.addStatement(new TryStmt(tryBlock, new NodeList<>(catchClause), finallyBlock));
        method.setBody(newBody);
    }
}
