# WinVMJ Environment Configuration
# Product: ${productName}
# Generated by WinVMJ Composer

# ============================================
# Backend Server Configuration
# ============================================
# Backend server host address
AMANAH_HOST_BE=localhost

# Backend server port number
AMANAH_PORT_BE=7776

# ============================================
# Database Configuration
# ============================================
# PostgreSQL connection URL (for Docker: use postgres as hostname)
AMANAH_DB_URL=jdbc:postgresql://postgres:5432/${productName?lower_case}

# Database username
AMANAH_DB_USERNAME=postgres

# Database password
AMANAH_DB_PASSWORD=postgres123

# ============================================
# Docker Port Mappings (HOST:CONTAINER)
# ============================================
# Note: Container internal ports are fixed (7776, 9464)
# These variables control which HOST ports map to them

# Backend server host port (maps to container:7776)
HOST_PORT_BE=7776

# PostgreSQL host port (maps to container:5432)
HOST_PORT_POSTGRES=5432

<#if hasMonitoringAspect>
# ============================================
# Monitoring Configuration
# ============================================
# Prometheus metrics host port (maps to container:9464)
HOST_PORT_MONITORING=9464
</#if>

# ============================================
# Usage Instructions
# ============================================
# For Docker Compose:
#   1. Copy this file to .env
#   2. Modify values as needed
#   3. Run: docker-compose up -d
#
# For Gradle (local development):
#   1. Copy to gradle.properties
#   2. Add prefix "systemProp." to each variable
#      Example: systemProp.AMANAH_DB_URL=jdbc:postgresql://localhost:5432/${productName?lower_case}
#
# For System Environment (Windows PowerShell):
#   ${"$"}env:AMANAH_DB_URL="jdbc:postgresql://localhost:5432/${productName?lower_case}"
